### ISSUE TITLE
AssertionError: Path does not exist: dataset/data/ImageSets/train.txt

### ISSUE THREAD

**Issue by crystalruo** [zhung2/uvtranse#1]
Hi,thanks for your sharing.I followed the instructions to put the files in the folder,but I have encountered  the following error when I run this command :python train.py --dataroot dataset/data

Traceback (most recent call last):
  File "train.py", line 93, in <module>
    train()
  File "train.py", line 15, in train
    train_dataset = VrdDataset(opt.dataroot, split='train', net=opt.feat_net, use_lang=opt.use_lang)
  File "/media/zbp/957174eb-3a01-447e-a596-2212be057407/home/zbp/yml/uvtranse-master/datasets/vrd.py", line 178, in __init__
    self._image_index = self._load_image_set_index()
  File "/media/zbp/957174eb-3a01-447e-a596-2212be057407/home/zbp/yml/uvtranse-master/datasets/vrd.py", line 367, in _load_image_set_index
    'Path does not exist: {}'.format(image_set_file)
AssertionError: Path does not exist: dataset/data/ImageSets/train.txt

I checked the folder,there were no folder named "ImageSets" and train.txt.Could you help me to solve this problem?Thank you very much.

**Comment by coldmanck** [comment]
Same here

**Comment by zhung2** [comment]
Sorry, you should comment out 
``
self._image_index = self._load_image_set_index()
``
in  ```datasets/vrd.py```. It is not used.
