### ISSUE TITLE
Problem with load pkl file 

### ISSUE THREAD

**Issue by kent252** [zhung2/uvtranse#5]
Dear scholar, thanks for your inspiring article, I try to run this but Perhaph I get into a problem:
Traceback (most recent call last):
  File "/content/drive/MyDrive/UVtransE/uvtranse/test.py", line 52, in <module>
    test_dataset = VrdDataset(opt.dataroot, split='test', net=opt.feat_net, use_gt=opt.use_gt, use_lang=opt.use_lang)
  File "/content/drive/MyDrive/UVtransE/uvtranse/datasets/vrd.py", line 162, in __init__
    self.data_dict = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb4 in position 1: ordinal not in range(128)

Could you help me with this

**Comment by kent252** [comment]
@zhung2
